name: ci
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install MaOS deps
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install sdl2 sdl2_image sdl2_mixer sdl2_ttf pkg-config
      - name: Install python dependencies
        run: |
          python3 -m pip install --break-system-packages --upgrade pip
          pip3 install --break-system-packages -r requirements.txt
      - name: Build on ${{ matrix.os }}
        run: |
          cd pyinstaller_builds
          python3 build.py
      - uses: actions/upload-artifact@v4
        with:
          name: PyCurveBug-build-${{ matrix.os }}
          path: pyinstaller_builds/dist/
          if-no-files-found: 'error'
  release:
    if: github.ref_type == 'tag'
    name: Upload release artifacts
    runs-on: ubuntu-latest
    needs: Build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: PyCurveBug*
      - name: Upload distribution
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.ref_name }}" PyCurveBug-build-*/PyCurveBug-*.tar.gz
          gh release upload "${{ github.ref_name }}" PyCurveBug-build-*/PyCurveBug-*.zip
